language: python
sudo: false
services: 
    - docker
install:
    - pip install -U fabric=1.14.0
script:
    - export CTAG="-$TRAVIS_COMMIT"
    - "fab docker_build" 
deploy:
    skip_cleanup: false
    provider: script
    script: "fab docker_build"
    on:
        branch: master

